proyecto/cms/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('loggedIn', views.loggedIn),
    path('logout', views.logout_view),
    path('<str:llave>', views.get_content),
  
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('cms/', include('cms.urls')),
    path('admin/', admin.site.urls),
    path('login', login.as_view()),
]

static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/cms/models.py
from django.db import models

# Create your models here.

class Contenido(models.Model):
    clave = models.CharField(max_length=64)
    valor = models.TextField()

    def __str__(self):
        return self.clave

    def tiene_as(self):
        return ('a' in self.valor)

class Comentario(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    cuerpo = models.TextField(blank=False)
    fecha = models.DateTimeField('publicado')

    def __str__(self):
        return self.titulo

proyecto/cms/views.py
# Create your views here.

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.template import loader

from .models import Contenido, Comentario

@csrf_exempt
def loggedIn(request):
    if request.user.is_authenticated:
        logged = "Logged in as " + request.user.username
    else:
        logged = "Not logged in. <a href='/admin/'>Login via admin</a>"
    return HttpResponse(logged)

@csrf_exempt
def logout_view(request):
    logout(request)
    return redirect("/cms/") 

@csrf_exempt
def get_content(request, llave):
    if request.method == "PUT":
        valor = request.body.decode('utf-8')           
    elif request.method == "POST":
        action = request.POST['action']
    if request.method == "POST" and action == "Enviar Contenido":
        valor = request.POST['valor']
    if request.method == "PUT" or (request.method == "POST" and action == "Enviar Contenido"):
        try:
            c = Contenido.objects.get(clave=llave)
            c.valor = valor
        except Contenido.DoesNotExist:
            c = Contenido(clave=llave, valor=valor)
        c.save()
    if request.method == "POST" and action == "Enviar Comentario":
            c = Contenido.objects.get(clave=llave)    
            titulo = request.POST['titulo']
            cuerpo = request.POST['cuerpo']
            q = Comentario(contenido=c, titulo=titulo, cuerpo=cuerpo, fecha=timezone.now())
            q.save()

    if request.user.is_authenticated:
        logged = True
        user_name = request.user.username
    else:
        logged = False
        user_name = ""

    contenido = get_object_or_404(Contenido, clave=llave)
    context = {'contenido': contenido, 'logged': logged, 'user_name': user_name}
    return render(request, 'cms/content.html', context)

def index(request):
    content_list = Contenido.objects.all()[:5]
    context = {'content_list': content_list}
    return render(request, 'cms/index.html', context)

proyecto/cms/templates/cms/content.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CMS USERS PUT</title>
  </head>
  <body style="background-color:#cccc67;">
    <center>
        {% if logged %}
          <p1>Logged in as {{ user_name }}. <a href='/cms/logout'>Logout</a></p1>
        {% else %}
         <p1>Not logged in. <a href='/admin/'>Login</a></p1>
        {% endif%}

        <h1>Contenido de {{ contenido.clave }}</h1>
        <h3>{{ contenido.valor }}</h3>
        <br>
        <br>

        <h1>Listado de comentarios</h1>
        {% if not contenido.comentario_set.all %}
        <p1>No hay comentarios disponibles.</p1>
        {% else %}
            {% for comentario in contenido.comentario_set.all %}
                <hr>
                <h2><li>{{ comentario.titulo }}</li></h2>
                    {{ comentario.cuerpo }}<br>
                    Enviado el {{ comentario.fecha }}<br>
            {% endfor %}
        {% endif %}
    </center>
        {% if logged %}
            <br>
            <br>
            <form action="" method="POST">
              <h2>Introduce el (nuevo) contenido para esta página:</h2><br>
              <input type="text" name="valor">
              <input type="submit" name="action" value="Enviar Contenido">
            </form>

            <br>
            <form action="" method="POST">
              <h2>Introduce un nuevo comentario para esta página:</h2>
              <br>Título: <input type="text" name="titulo">
              <br>Cuerpo: <input type="text" name="cuerpo">
              <input type="submit" name="action" value="Enviar Comentario">
            </form>
        {% endif%}
</body>

proyecto/cms/templates/cms/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CMS MENU</title>
  </head>
  <body style="background-color:#cccc67;">
      <center>
          <h1>Lista de contenidos</h1>
        {% if content_list %}
            <ul>
            {% for content in content_list %}
                <li><a href="/cms/{{ content.clave }}">{{ content.clave }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No hay contenidos disponibles.</p>
        {% endif %}

proyecto/cms/templates/cms/plantilla.html
{% load static %}
<img src="{% static "cms/example.jpg" %}" alt="My image">